### ISSUE TITLE
Disallow referencing steps of a subproofs

### ISSUE THREAD

**Issue by kovzol** [kovzol/aris#6]
Currently it is allowed to refer to a step of a subproof, but this is clearly an error. In a subproof we can assume a false statement and derive anything (including the obviously false statement too). So only non-subproof steps should be allowed as a reference.

**Comment by kovzol** [comment]
Thanks for the fix. Please can you add some comments why you chose validref_lim = 100 and stack_lim = 25 as initial values? Also, please add some comments what you are exactly doing in your fix. Thank you!

**Comment by sucksome** [comment]
I chose validref_lim as 100 as I thought 100 lines in a proof is a good enough initial value, if the proof becomes longer, validref_lim is increased and the validref_lines array is reallocated. 
Similarly with stack_lim, since the stack stores (nested) open subproofs I thought initial value of 25 is good enough.

What the fix does:
We initialize an array with all elements equal 0, each index of the array represents a line number in the proof. 
We traverse down the proof (by the means of aris_create_sentence ), if a new subproof is opened, that line number is added to the stack. When the subproof is closed, the stack is popped and we set the array from the popped index to current index = 1. 
A value of 1 represents that the line number given by that index cannot act as a reference while a value of 0 is allowed to do so.  
This restriction is implemented in select_reference inside sentence.c. However, we also add another condition that allows the line just after a subproof ends to refer to the subproof, because that line may use the rule 'sp' .
